### ISSUE TITLE
How to build on Ubuntu

### ISSUE THREAD

**Issue by manhha1402** [icemiliang/lscm#1]
Hi,
I want to try your code. I found that it has no Makefile (I am not familiar with config.mk also). I created a cmakelist and build the repo but it has the error in the Parse.h: "SList.h: No such file or directory". What is SList.h and how can I have it?
Thanks

**Comment by icemiliang** [comment]
Hi,

I have added the makefiles. I just tested it with a fresh clone and build
on my computer. It should work now.

Thanks,

**Comment by manhha1402** [comment]
Hi,
If I have a texture mesh (obj file) with multiple texture maps (RGB images). Is it possible to generate a single texture atlas from multiple RGB images ? What should I modify in your code to have it ? Cause I am using a software to generate it, I just want to use code base.
For example, some thing like this texture atlas:
![textured_material0000_map_kd](https://user-images.githubusercontent.com/20105284/48678924-3e6ac900-eb8a-11e8-93af-654081e6e70c.png)

Thanks

**Comment by icemiliang** [comment]
Hi,

I am not sure what this texture atlas should be. Is it the average of the
RGB images?

**Comment by icemiliang** [comment]
Do you have the correspondence between the mesh and each of the images?

**Comment by manhha1402** [comment]
[mesh.zip](https://github.com/icemiliang/lscm/files/2612965/mesh.zip)
Hi,
attached file is texture mesh with multiple texture maps. OBJ file contains all correspondences. I want to merge all texture maps into one or more texture atlas. I think the paper "Least squares conformal maps for automatic texture atlas generation." can do that.
Thanks

**Comment by icemiliang** [comment]
I see. Sorry, this beyond my knowledge. I only implemented the conformal mapping part, for the segmentation and packing parts, I guess you have to contact the authors of the paper or take a look at their code if available.

**Comment by manhha1402** [comment]
Thanks !
