### ISSUE TITLE
List is not a template

### ISSUE THREAD

**Issue by simonpasi-ensam** [icemiliang/lscm#10]
Sorry if this is a dumb question, but I get this error when I try to build,
`E0864 - List is not a template`
I'm very new to c++ and I'm not sure what to do, should I create the List class myself?

**Comment by icemiliang** [comment]
Could you show the commands and full console output when you build? @simonpasi-ensam

**Comment by simonpasi-ensam** [comment]
For the commands, I just wrote them in the main.cpp file
`mesh.read_obj("../data/human.obj"/*argv[1]*/);`
`mesh.write_obj("output.obj"/*argv[2]*/);`
Here's the console output:
![Screenshot 2020-09-22 101529](https://user-images.githubusercontent.com/62236570/93858529-9578e200-fcbc-11ea-92d3-4fa8195e56d2.jpg)

**Comment by icemiliang** [comment]
Did you try the original main function? The readme file has the instruction to build it and test it with the data.

**Comment by simonpasi-ensam** [comment]
Ha I was not following the build instructions >_>
Thank you, it works now 👍

**Comment by icemiliang** [comment]
No problem! Glad it worked.
