### ISSUE TITLE
How to fix the vertices?

### ISSUE THREAD

**Issue by Kiddo1024** [icemiliang/lscm#12]
Excuse me. Could you please tell me how to fix the vertices of my obj?

**Comment by daeunSong** [comment]
You can do it by simply modifying your obj file with the text editor.
Please refer to line [679](https://github.com/icemiliang/lscm/blob/544fe7256e35f444136bff25e8b68f869a7481d1/data/human.obj#L679) and [3594](https://github.com/icemiliang/lscm/blob/544fe7256e35f444136bff25e8b68f869a7481d1/data/human.obj#L3594) in data/human.obj file in the repo.

**Comment by icemiliang** [comment]
Thanks @daeunSong. Yes, that's exactly how the code works. 

Hi @Kiddo102, please check readme for details. 

I'm closing the issue for now, but feel free to continue the discussion if needed.
