### ISSUE TITLE
How can I adapt this project to work with watertight meshes?

### ISSUE THREAD

**Issue by Lotayou** [icemiliang/lscm#5]
Hi, thanks for your amazing work. However I've encountered the following error while testing with my own mesh model:

```
(eric) vcl@vcl-dl-2:/backup1/eric/lscm$ sh test_watertight.sh
make -C src clean
make[1]: 进入目录“/backup1/eric/lscm/src”
rm -f Boundary.o lscm.o Edge.o Face.o FormTrait.o HalfEdge.o Homology.o Mesh.o Vertex.o Graph.o
rm -f libmesh++.a
make[1]: 离开目录“/backup1/eric/lscm/src”
rm -f main
make -C src
make[1]: 进入目录“/backup1/eric/lscm/src”
g++ -Wall -pedantic -O3 -std=c++11 -Isrc/ -I/usr/include/ -Iinclude/ -I../include/ -c Boundary.cpp
g++ -Wall -pedantic -O3 -std=c++11 -Isrc/ -I/usr/include/ -Iinclude/ -I../include/ -c lscm.cpp
lscm.cpp: In member function ‘void MeshLib::LSCM::parameterize()’:
lscm.cpp:68:39: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘std::vector<MeshLib::Vertex*>::size_type {aka long unsigned int}’ [-Wformat=]
   printf("%d\n", m_fix_vertices.size());
                  ~~~~~~~~~~~~~~~~~~~~~^
g++ -Wall -pedantic -O3 -std=c++11 -Isrc/ -I/usr/include/ -Iinclude/ -I../include/ -c Edge.cpp
g++ -Wall -pedantic -O3 -std=c++11 -Isrc/ -I/usr/include/ -Iinclude/ -I../include/ -c Face.cpp
g++ -Wall -pedantic -O3 -std=c++11 -Isrc/ -I/usr/include/ -Iinclude/ -I../include/ -c FormTrait.cpp
g++ -Wall -pedantic -O3 -std=c++11 -Isrc/ -I/usr/include/ -Iinclude/ -I../include/ -c HalfEdge.cpp
g++ -Wall -pedantic -O3 -std=c++11 -Isrc/ -I/usr/include/ -Iinclude/ -I../include/ -c Homology.cpp
g++ -Wall -pedantic -O3 -std=c++11 -Isrc/ -I/usr/include/ -Iinclude/ -I../include/ -c Mesh.cpp
g++ -Wall -pedantic -O3 -std=c++11 -Isrc/ -I/usr/include/ -Iinclude/ -I../include/ -c Vertex.cpp
g++ -Wall -pedantic -O3 -std=c++11 -Isrc/ -I/usr/include/ -Iinclude/ -I../include/ -c Graph.cpp
rm -f libmesh++.a
ar rs libmesh++.a Boundary.o lscm.o Edge.o Face.o FormTrait.o HalfEdge.o Homology.o Mesh.o Vertex.o Graph.o
ar: 正在创建 libmesh++.a
make[1]: 离开目录“/backup1/eric/lscm/src”
g++ -Wall -pedantic -O3 -std=c++11 -Isrc/ -I/usr/include/ -Iinclude/ -I../include/ -Lsrc/ -L/usr/lib/ -o main main.cpp -lmesh++
--> Reading mesh...
--> Computing conformal map...
0
main: lscm.cpp:69: void MeshLib::LSCM::parameterize(): Assertion `m_fix_vertices.size()>=2' failed.
Aborted (core dumped)
```

It seems that my model lacks some "fix vertices", which should be greater than zero (while my model got none). I find that the only difference is that my input mesh is genus-0 and watertight while your mesh contains clear "boundary". 

I'm wondering what does "fix vertices" mean? Furthermore, can you show me a quick workaround for dealing with watertight meshes? Many thanks!

**Comment by icemiliang** [comment]
Hello,
If you can open human.obj and search for "fix", there are two vertices having that after the xyz coordinates. The README.md file has covered this in Usage. 

As for the water-tight mesh, LSCM does not apply to water-tight meshes. If you check the original paper by Lévy (which is referenced in readme), you will find that the purpose of LSCM is to map meshes onto a planar domain with minimum distortion. To do that, the first step is to decompose the mesh into smaller pieces with boundaries. Then, Lévy computes the LSCM for each piece. 

So, I think it depends on your application. If you have a similar application as Lévy, then you can follow the same steps. If you want to map one or more water-tight meshes into a common space which does not have to be planar, you can use the [spherical harmonic mapping](https://github.com/icemiliang/geometry-processing-package/blob/master/parameterization/spherical_conformal_map.m). Let me know if you have further questions.

**Comment by icemiliang** [comment]
> Hi, thanks for your amazing work. However I've encountered the following error while testing with my own mesh model:
> 
> ```
> (eric) vcl@vcl-dl-2:/backup1/eric/lscm$ sh test_watertight.sh
> make -C src clean
> make[1]: 进入目录“/backup1/eric/lscm/src”
> rm -f Boundary.o lscm.o Edge.o Face.o FormTrait.o HalfEdge.o Homology.o Mesh.o Vertex.o Graph.o
> rm -f libmesh++.a
> make[1]: 离开目录“/backup1/eric/lscm/src”
> rm -f main
> make -C src
> make[1]: 进入目录“/backup1/eric/lscm/src”
> g++ -Wall -pedantic -O3 -std=c++11 -Isrc/ -I/usr/include/ -Iinclude/ -I../include/ -c Boundary.cpp
> g++ -Wall -pedantic -O3 -std=c++11 -Isrc/ -I/usr/include/ -Iinclude/ -I../include/ -c lscm.cpp
> lscm.cpp: In member function ‘void MeshLib::LSCM::parameterize()’:
> lscm.cpp:68:39: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘std::vector<MeshLib::Vertex*>::size_type {aka long unsigned int}’ [-Wformat=]
>    printf("%d\n", m_fix_vertices.size());
>                   ~~~~~~~~~~~~~~~~~~~~~^
> g++ -Wall -pedantic -O3 -std=c++11 -Isrc/ -I/usr/include/ -Iinclude/ -I../include/ -c Edge.cpp
> g++ -Wall -pedantic -O3 -std=c++11 -Isrc/ -I/usr/include/ -Iinclude/ -I../include/ -c Face.cpp
> g++ -Wall -pedantic -O3 -std=c++11 -Isrc/ -I/usr/include/ -Iinclude/ -I../include/ -c FormTrait.cpp
> g++ -Wall -pedantic -O3 -std=c++11 -Isrc/ -I/usr/include/ -Iinclude/ -I../include/ -c HalfEdge.cpp
> g++ -Wall -pedantic -O3 -std=c++11 -Isrc/ -I/usr/include/ -Iinclude/ -I../include/ -c Homology.cpp
> g++ -Wall -pedantic -O3 -std=c++11 -Isrc/ -I/usr/include/ -Iinclude/ -I../include/ -c Mesh.cpp
> g++ -Wall -pedantic -O3 -std=c++11 -Isrc/ -I/usr/include/ -Iinclude/ -I../include/ -c Vertex.cpp
> g++ -Wall -pedantic -O3 -std=c++11 -Isrc/ -I/usr/include/ -Iinclude/ -I../include/ -c Graph.cpp
> rm -f libmesh++.a
> ar rs libmesh++.a Boundary.o lscm.o Edge.o Face.o FormTrait.o HalfEdge.o Homology.o Mesh.o Vertex.o Graph.o
> ar: 正在创建 libmesh++.a
> make[1]: 离开目录“/backup1/eric/lscm/src”
> g++ -Wall -pedantic -O3 -std=c++11 -Isrc/ -I/usr/include/ -Iinclude/ -I../include/ -Lsrc/ -L/usr/lib/ -o main main.cpp -lmesh++
> --> Reading mesh...
> --> Computing conformal map...
> 0
> main: lscm.cpp:69: void MeshLib::LSCM::parameterize(): Assertion `m_fix_vertices.size()>=2' failed.
> Aborted (core dumped)
> ```
> It seems that my model lacks some "fix vertices", which should be greater than zero (while my model got none). I find that the only difference is that my input mesh is genus-0 and watertight while your mesh contains clear "boundary".
> 
> I'm wondering what does "fix vertices" mean? Furthermore, can you show me a quick workaround for dealing with watertight meshes? Many thanks!

Hello,
If you can open human.obj and search for "fix", there are two vertices having that after the xyz coordinates. The README.md file has covered this in Usage.

As for the water-tight mesh, LSCM does not apply to water-tight meshes. If you check the original paper by Lévy (which is referenced in readme), you will find that the purpose of LSCM is to map meshes onto a planar domain with minimum distortion. To do that, the first step is to decompose the mesh into smaller pieces with boundaries. Then, Lévy computes the LSCM for each piece.

So, I think it depends on your application. If you have a similar application as Lévy, then you can follow the same steps. If you want to map one or more water-tight meshes into a common space which does not have to be planar, you can use the [spherical harmonic mapping](https://github.com/icemiliang/geometry-processing-package/blob/master/parameterization/spherical_conformal_map.m). An alternative which I don't recommend is to cut a small hole on the mesh, maybe by removing a triangle or a few triangles, and then map the whole mesh on to the planar domain. This time LSCM may not work well because there is too much distortion. You can try [disc harmonic mapping](https://github.com/icemiliang/geometry-processing-package/blob/master/parameterization/disk_harmonic_map.m) instead.  Let me know if you have further questions.

**Comment by Lotayou** [comment]
Thanks for your advice! I'll look into it and let you know of my progress. 
BTW, I'm working with human body meshes, so I guess it's okay to cut a mesh into pieces of skins and apply textures separately. It's just somewhat tricky to consider the stitching issue.

**Comment by icemiliang** [comment]
> Thanks for your advice! I'll look into it and let you know of my progress.
> BTW, I'm working with human body meshes, so I guess it's okay to cut a mesh into pieces of skins and apply textures separately. It's just somewhat tricky to consider the stitching issue.

You can cut the mesh into different pieces and map all the pieces to the same planar domain. Change the fixed 2D positions mentioned in readme to avoid overlap. For each vertex, you get the correspondence between its 3D position and 2D position. Apply the texture on 2D and then use the correspondence to apply the texture on 3D. No stitching is needed.

**Comment by icemiliang** [comment]
I am closing the issue for now.
