### ISSUE TITLE
2 points are  less in output.obj compare to input.obj file

### ISSUE THREAD

**Issue by rupeshchandgude** [icemiliang/lscm#7]
I have tested code on my test file. Code run without error, but the number of points in output file is less compare to input file by 2 points. I had fixed 2 points in input file as per you suggested in repository.Is there any thing going wrong? I had attached the test file below.
test_file = [test_simple_sample.obj.zip](https://github.com/icemiliang/lscm/files/3609144/test_simple_sample.obj.zip)

Number of points in input file = 63
Number of points in output file = 61

**Comment by icemiliang** [comment]
Vertex 15 and 59 are not in any triangles. Could you verify the mesh?

**Comment by rupeshchandgude** [comment]
@icemiliang  Yes this unassigned points are missing form output mesh. So basically input mesh should not have any unassigned points in it. Is it correct?

**Comment by icemiliang** [comment]
@rupeshchandgude After loading the vertices and faces, MeshLib will build a half-edge connection of all the vertices and faces. Isolated vertices will then be removed, so the output will not have those vertices.

**Comment by rupeshchandgude** [comment]
@icemiliang  Thanks for clarification.
